require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BasicsController do

  # This should return the minimal set of attributes required to create a valid
  # Basic. As you add validations to Basic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BasicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all basics as @basics" do
      basic = Basic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:basics).should eq([basic])
    end
  end

  describe "GET show" do
    it "assigns the requested basic as @basic" do
      basic = Basic.create! valid_attributes
      get :show, {:id => basic.to_param}, valid_session
      assigns(:basic).should eq(basic)
    end
  end

  describe "GET new" do
    it "assigns a new basic as @basic" do
      get :new, {}, valid_session
      assigns(:basic).should be_a_new(Basic)
    end
  end

  describe "GET edit" do
    it "assigns the requested basic as @basic" do
      basic = Basic.create! valid_attributes
      get :edit, {:id => basic.to_param}, valid_session
      assigns(:basic).should eq(basic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Basic" do
        expect {
          post :create, {:basic => valid_attributes}, valid_session
        }.to change(Basic, :count).by(1)
      end

      it "assigns a newly created basic as @basic" do
        post :create, {:basic => valid_attributes}, valid_session
        assigns(:basic).should be_a(Basic)
        assigns(:basic).should be_persisted
      end

      it "redirects to the created basic" do
        post :create, {:basic => valid_attributes}, valid_session
        response.should redirect_to(Basic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved basic as @basic" do
        # Trigger the behavior that occurs when invalid params are submitted
        Basic.any_instance.stub(:save).and_return(false)
        post :create, {:basic => { "name" => "invalid value" }}, valid_session
        assigns(:basic).should be_a_new(Basic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Basic.any_instance.stub(:save).and_return(false)
        post :create, {:basic => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested basic" do
        basic = Basic.create! valid_attributes
        # Assuming there are no other basics in the database, this
        # specifies that the Basic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Basic.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => basic.to_param, :basic => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested basic as @basic" do
        basic = Basic.create! valid_attributes
        put :update, {:id => basic.to_param, :basic => valid_attributes}, valid_session
        assigns(:basic).should eq(basic)
      end

      it "redirects to the basic" do
        basic = Basic.create! valid_attributes
        put :update, {:id => basic.to_param, :basic => valid_attributes}, valid_session
        response.should redirect_to(basic)
      end
    end

    describe "with invalid params" do
      it "assigns the basic as @basic" do
        basic = Basic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Basic.any_instance.stub(:save).and_return(false)
        put :update, {:id => basic.to_param, :basic => { "name" => "invalid value" }}, valid_session
        assigns(:basic).should eq(basic)
      end

      it "re-renders the 'edit' template" do
        basic = Basic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Basic.any_instance.stub(:save).and_return(false)
        put :update, {:id => basic.to_param, :basic => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested basic" do
      basic = Basic.create! valid_attributes
      expect {
        delete :destroy, {:id => basic.to_param}, valid_session
      }.to change(Basic, :count).by(-1)
    end

    it "redirects to the basics list" do
      basic = Basic.create! valid_attributes
      delete :destroy, {:id => basic.to_param}, valid_session
      response.should redirect_to(basics_url)
    end
  end

end
